.TH TEAM_MONITOR 1 "2013-07-10" "libteam" "team monitor"
.SH NAME
team_monitor \(em team network device monitor
.SH SYNOPSIS
.B team_monitor
.B TEAMDEV
.SH DESCRIPTION
.PP
team_monitor is an activity monitor for a configured team network device.
.SH SEE ALSO
.BR teamdctl (8),
.BR teamd.conf (5),
.BR teamnl (8),
.BR bond2team (1)
.SH AUTHOR
.PP
Jiri Pirko is the original author and current maintainer of libteam.
